### ISSUE TITLE
Cambio de contraseña

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/MessageApp#15]
Generar funcionalidad para cambiar de contraseña desde la configuración del perfil.

- [ ] Se tiene que poder cambiar la contraseña desde la configuración de perfil.
- [ ] Se tiene que recuperar la contraseña desde el inicio de sesión en caso de olvidar contraseña.
- [ ] Enviar código PIN de 6 dígitos para cambiar contraseña o recuperar contraseña.

**Comment by AlanMartell14** [comment]
Se comprobo el funcionamiento, tanto de verificacion de correo electronico (sendEmailVerification) y tambien la funcion de recuperar contraseña (resetPasswordByEmail) estas funciones fueron agregadas y exitosamente funcionales, el usuario puede ingresar si tiene un correo existente, todo esto son funciones integras de firebase y adaptadas a Angular CLI

**Comment by AlanMartell14** [comment]
Agregue y actualice librerías para la agilización del servicio de firebase y automatización de este "authentication"
