### ISSUE TITLE
Configuración de Dominio

### ISSUE THREAD

**Issue by erickmerchant05** [Adolf0M/MessageApp#23]

**Comment by erickmerchant05** [comment]
Configuración de dominio (De no contar con una, usar un DDNS (no-ip, dyndns, … ), ngrok, o code spaces). Con la finalidad de que sea visible a todo público.

**Comment by erickmerchant05** [comment]
Estoy intentando subir por filezilla. Se compro mebresia de HOST de IONOS. Tengo el problema que no muestra nada el host. 



![Image](https://github.com/Adolf0M/MessageApp/assets/126835786/953aaa86-e958-4dd8-a636-1efc8100d58c)

**Comment by Adolf0M** [comment]
Tienes que hacer el `ng build` antes de querer hacer el deploy

**Comment by erickmerchant05** [comment]
Se logro subir proyecto a hosting

![Image](https://github.com/Adolf0M/MessageApp/assets/126835786/aafa4d6a-98b9-4dbb-9c03-c7ff65e040c4)

**Comment by erickmerchant05** [comment]
http://message-app.online/#/login

**Comment by erickmerchant05** [comment]
Conexion exitosa
