### ISSUE TITLE
Backend para login y register

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/MessageApp#5]
Enlazar auth con token de firebase con front de login y register

**Comment by AlanMartell14** [comment]
Se realizó enlace auth con token generado por firebase #5

**Comment by AlanMartell14** [comment]
Fue necesario instalar la dependencia de "firebase" para la ejecución del "authentication" el login, register y el navbar contiene funciones nuevas cómo singUp(), loginWithGoogle(), login() y logOut() estas funciones fueron agregadas gracias al auth.services.ts y exportadas, se genero un "environment" y el "app.config.ts" fue modificado.
