### ISSUE TITLE
Proteger rutas

### ISSUE THREAD

**Issue by Adolf0M** [Adolf0M/MessageApp#6]
Proteger rutas para que solo se pueda acceder a home una vez se haya iniciado sesion con token

**Comment by AlanMartell14** [comment]
Se ha protegido las rutas de manera exitosa, ahora existe un "publicGuard" donde se encuentran las ramas de "register" y "login" mientras que existe otro apartado llamado privateGuard donde reserva la información de los usuarios en la mensajería online, esta protección se encuentra en: "src/app/core/guards/auth.guards.ts" y se protegio el enrutado llamado a dichas funciones en "app.route.ts"
